MvcCrudDepartamentosAdo/Models/Departamento.cs
namespace MvcCrudDepartamentosAdo.Models
{
    public class Departamento
    {
        public int IdDepartamento { get; set; }
        public string Nombre { get; set; }
        public string Localidad { get; set; }
    }
}

MvcCrudDepartamentosAdo/Models/ErrorViewModel.cs
namespace MvcCrudDepartamentosAdo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCrudDepartamentosAdo/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCrudDepartamentosAdo.Models;
using MvcCrudDepartamentosAdo.Repositories;

namespace MvcCrudDepartamentosAdo.Controllers
{
    public class DepartamentosController : Controller
    {
        private RepositoryDepartamentos repo;

        public DepartamentosController()
        {
            this.repo = new RepositoryDepartamentos();
        }

        public IActionResult Index()
        {
            List<Departamento> departamentos =
                this.repo.GetDepartamentos();
            return View(departamentos);
        }

        public IActionResult Details(int iddepartamento)
        {
            Departamento departamento =
                this.repo.FindDepartamento(iddepartamento);
            return View(departamento);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Departamento departamento)
        {
            this.repo.InsertDepartamento(departamento.IdDepartamento
                , departamento.Nombre, departamento.Localidad);
            ViewData["MENSAJE"] = "Departamento insertado";
            //return View("Index");
            //EXISTE UN METODO LLAMADO RedirectToAction
            //QUE NO MANDA A UNA VISTA, SINO QUE MANDA AL ACTION
            return RedirectToAction("Index");
        }

        //PARA ELIMINAR NO VAMOS A TENER NINGUNA VISTA
        //DIRECTAMENTE PONDREMOS UN ENLACE DENTRO DE Index.cshtml
        //Y QUE LLAME A ESTE METODO.
        //DESPUES DE LEER EL METODO, LO LLEVAMOS A INDEX
        public IActionResult Delete(int iddepartamento)
        {
            this.repo.DeleteDepartamento(iddepartamento);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int iddepartamento)
        {
            Departamento departamento =
                this.repo.FindDepartamento(iddepartamento);
            return View(departamento);
        }

        [HttpPost]
        public IActionResult Update(Departamento departamento)
        {
            this.repo.UpdateDepartamento(departamento.IdDepartamento
                , departamento.Nombre, departamento.Localidad);
            return RedirectToAction("Index");
        }
    }
}

MvcCrudDepartamentosAdo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCrudDepartamentosAdo.Models;
using System.Diagnostics;

namespace MvcCrudDepartamentosAdo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCrudDepartamentosAdo/Views/Departamentos/Create.cshtml
<h1>Nuevo departamento</h1>

<form method="post">
    <label>Id departamento: </label>
    <input type="text" name="iddepartamento"
        class="form-control" required />
    <label>Nombre: </label>
    <input type="text" name="nombre"
        class="form-control" required/>
    <label>Localidad: </label>
    <input type="text" name="localidad"
        class="form-control" required/>
    <button class="btn btn-info">
        Create
    </button>
</form>
<h2 style="color:fuchsia">@ViewData["MENSAJE"]</h2>

MvcCrudDepartamentosAdo/Views/Departamentos/Details.cshtml
@model Departamento

<a asp-controller="Departamentos"
    asp-action="Index">
    Volver a Index
</a>

<ul class="list-group">
    <li class="list-group-item">
        Id departamento: @Model.IdDepartamento
    </li>
    <li class="list-group-item">
        Nombre: @Model.Nombre
    </li>
    <li class="list-group-item">
        Localidad: @Model.Localidad
    </li>
</ul>

MvcCrudDepartamentosAdo/Views/Departamentos/Index.cshtml
@model List<Departamento>

<h1 style="color:blue">
        Listado departamentos
</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>NOMBRE</th>
            <th>LOCALIDAD</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Departamento dept in Model)
        {
            <tr>
                <td>@dept.IdDepartamento</td>
                <td>@dept.Nombre</td>
                <td>@dept.Localidad</td>
                <td>
                    @Html.ActionLink("Details", "Details", "Departamentos"
                    , new { iddepartamento = dept.IdDepartamento}) | 
                    @Html.ActionLink("Delete", "Delete", "Departamentos"
                    , new { iddepartamento = dept.IdDepartamento}) | 
                    @Html.ActionLink("Update", "Update", "Departamentos"
                    , new {iddepartamento = dept.IdDepartamento})
                </td>
            </tr>
        }
    </tbody>
</table>

MvcCrudDepartamentosAdo/Views/Departamentos/Update.cshtml
@model Departamento

<h1>Edit departamento</h1>

<a asp-controller="Departamentos"
    asp-action="Index">
    Volver a Index
</a>
<hr/>
<form method="post">
    <input type="hidden" name="iddepartamento" value="@Model.IdDepartamento"/>
    <label>Nombre: </label>
    <input type="text" name="nombre" value="@Model.Nombre"
        class="form-control" required/>
    <label>Localidad: </label>
    <input type="text" name="localidad" value="@Model.Localidad"
        class="form-control" required/>
    <button class="btn btn-outline-dark">
        Update
    </button>
</form>

MvcCrudDepartamentosAdo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCrudDepartamentosAdo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCrudDepartamentosAdo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCrudDepartamentosAdo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/wolverine.jpg" style="width: 40px"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                asp-controller="Departamentos" 
                                asp-action="Index">
                                Departamentos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" 
                                asp-controller="Departamentos" 
                                asp-action="Create">
                                Nuevo Departamento
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCrudDepartamentosAdo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>